### ISSUE TITLE
Phonegap build

### ISSUE THREAD

**Issue by vielhuber** [VVelda/device-feedback#1]
Hello!

Thanks for the awesome plugin.

Is it possible to provide this plugin in the "official" 3rd party plugin repository at Phonegap?

Another question: Are you planning to expand this plugin also for iOS?

Best greets
David

**Comment by VVelda** [comment]
Hello, thank you.

Well, I have to change license from 2-clause BSD to MIT... I don't know, why
Adobe need (unreadable) MIT (or that very loooong Apache 2.0) license. :-) I
will look at it.

I'm planning iOS version, but there are two things.

Firstly, I'm not sure, if it's possible on iOS in the same way that on 
Android. And secondly, in present, I don't have any iOS device to test code.
:-(

Velda

---------- Původní zpráva ----------

Od: vielhuber notifications@github.com

Komu: VVelda/device-feedback device-feedback@noreply.github.com

Datum: 2. 8. 2014 11:59:07

Předmět: [device-feedback] Phonegap build (#1)

"

Hello!

Thanks for the awesome plugin.

Is it possible to provide this plugin in the "official" 3rd party plugin 
repository at Phonegap?

Another question: Are you planning to expand this plugin also for iOS?

Best greets

David

—

Reply to this email directly or view it on GitHub
(https://github.com/VVelda/device-feedback/issues/1). 

"

**Comment by VVelda** [comment]
Seems it on a good way – http://community.phonegap.com/nitobi/topics/restriction_to_mit_and_apache_2_0_license_only to accept 2-clause BSD on PhoneGap Build. You can vote up that topic if you want to. :-)

**Comment by vielhuber** [comment]
Hello!

Awesome, I voted it up!

Can’t wait for iOS support and phonegap build support!

Best greets
David

Von: Jan Velecký [mailto:notifications@github.com]
Gesendet: Freitag, 15. August 2014 12:56
An: VVelda/device-feedback
Cc: david@vielhuber.de
Betreff: Re: [device-feedback] Phonegap build (#1)

Seems it on a good way – http://community.phonegap.com/nitobi/topics/restriction_to_mit_and_apache_2_0_license_only to accept 2-clause BSD on PhoneGap Build. You can vote up that topic if you want to. :-)

**Comment by Pentaxeros** [comment]
Hi, I am interested to use this pluguin in phonegap build.

I would also support for iOS.

How are things?

Thank you

**Comment by VVelda** [comment]
Hello,
thank you for your interest. With Phonegap Build, there is a new problem. Described here: http://community.phonegap.com/nitobi/topics/cant-submit-my-plugin
As I am not Phonegap Build paid user (nor non-paid user), I'm not able to upload this plugin into Phonegap Build repository. This is Adobe restriction...

And iOS version... I would like to make it, but I don't have iOS device to test it on. I expected that my cousin lend me iPhone, but I haven't met him since that time, we are not in the same city. I try borrow device from someone else, but in our country iOS is not as popular as Android, not even as WP.

Have a good day.

**Comment by Pentaxeros** [comment]
From which country are you from?

2014-10-17 13:04 GMT+02:00 Jan Velecký notifications@github.com:

> Hello,
> thank you for your interest. With Phonegap Build, there is a new problem.
> Described here:
> http://community.phonegap.com/nitobi/topics/cant-submit-my-plugin
> As I am not Phonegap Build paid user (nor non-paid user), I'm not able to
> upload this plugin into Phonegap Build repository. This is Adobe
> restriction...
> 
> And iOS version... I would like to make it, but I don't have iOS device to
> test it on. I expected that my cousin lend me iPhone, but I haven't met him
> since that time, we are not in the same city. I try borrow device from
> someone else, but in our country iOS is not as popular as Android, not even
> as WP.
> 
> Have a good day.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/VVelda/device-feedback/issues/1#issuecomment-59497951
> .

## 

Según lo que dispone la Ley Orgánica 15/1999, de 13 de diciembre, de
Protección de Datos de Carácter Personal, le informamos que sus datos,
serán incorporados en un fichero de clientes titularidad de FOTOGRAFÍA Y
GESTIÓN PENTAXEROS, S.L., con el objeto de mantenerle informado por
cualquier medio (incluido el correo electrónico) del seguimiento de su
compra online, así como, de nuestros productos o servicios.
Asimismo, le informamos que puede ejercer los derechos de acceso,
rectificación, cancelación y oposición mediante carta dirigida a FOTOGRAFÍA
Y GESTIÓN PENTAXEROS, S.L., adjuntando fotocopia de su DNI, a C/ Constanza
núm. 5, CP 08028 de Barcelona o mediante correo electrónico a
pentaxeros@gmail.com.

**Comment by Pentaxeros** [comment]
Hi I've seen where you are.
I see that a contribution can help you develop.
I will work with you with a donation, so you can finish developing and
publishing PhoneGap Build and get an iphone.

If someone else wants to help, I encourage you to do so.

Greetings !!

2014-10-17 16:04 GMT+02:00 Pentaxeros.com pentaxeros@gmail.com:

> From which country are you from?
> 
> 2014-10-17 13:04 GMT+02:00 Jan Velecký notifications@github.com:
> 
> > Hello,
> > thank you for your interest. With Phonegap Build, there is a new problem.
> > Described here:
> > http://community.phonegap.com/nitobi/topics/cant-submit-my-plugin
> > As I am not Phonegap Build paid user (nor non-paid user), I'm not able to
> > upload this plugin into Phonegap Build repository. This is Adobe
> > restriction...
> > 
> > And iOS version... I would like to make it, but I don't have iOS device
> > to test it on. I expected that my cousin lend me iPhone, but I haven't met
> > him since that time, we are not in the same city. I try borrow device from
> > someone else, but in our country iOS is not as popular as Android, not even
> > as WP.
> > 
> > Have a good day.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/VVelda/device-feedback/issues/1#issuecomment-59497951
> > .
> 
> ## 
> 
> Según lo que dispone la Ley Orgánica 15/1999, de 13 de diciembre, de
> Protección de Datos de Carácter Personal, le informamos que sus datos,
> serán incorporados en un fichero de clientes titularidad de FOTOGRAFÍA Y
> GESTIÓN PENTAXEROS, S.L., con el objeto de mantenerle informado por
> cualquier medio (incluido el correo electrónico) del seguimiento de su
> compra online, así como, de nuestros productos o servicios.
> Asimismo, le informamos que puede ejercer los derechos de acceso,
> rectificación, cancelación y oposición mediante carta dirigida a FOTOGRAFÍA
> Y GESTIÓN PENTAXEROS, S.L., adjuntando fotocopia de su DNI, a C/ Constanza
> núm. 5, CP 08028 de Barcelona o mediante correo electrónico a
> pentaxeros@gmail.com.

## 

Según lo que dispone la Ley Orgánica 15/1999, de 13 de diciembre, de
Protección de Datos de Carácter Personal, le informamos que sus datos,
serán incorporados en un fichero de clientes titularidad de FOTOGRAFÍA Y
GESTIÓN PENTAXEROS, S.L., con el objeto de mantenerle informado por
cualquier medio (incluido el correo electrónico) del seguimiento de su
compra online, así como, de nuestros productos o servicios.
Asimismo, le informamos que puede ejercer los derechos de acceso,
rectificación, cancelación y oposición mediante carta dirigida a FOTOGRAFÍA
Y GESTIÓN PENTAXEROS, S.L., adjuntando fotocopia de su DNI, a C/ Constanza
núm. 5, CP 08028 de Barcelona o mediante correo electrónico a
pentaxeros@gmail.com.

**Comment by VVelda** [comment]
One thing... I had iPhone for two minutes a few days ago :-D, but I discover, there is not any acoustic touch feedback on buttons. But I thought iOS have acoustic touch feedback. How is it in real?

**Comment by vielhuber** [comment]
Hello!

They don’t have one in general,
but we want through your awesome plugin one!

Thanks in advance
David

---

e: david@vielhuber.demailto:david@vielhuber.de
w: www.vielhuber.dehttp://www.vielhuber.de/
t: 089-21555122
f: 089-21555122-9

## l: e=email, w=web, t=telefon, f=fax, l=legende

Von: Jan Velecký [mailto:notifications@github.com]
Gesendet: Mittwoch, 29. Oktober 2014 21:26
An: VVelda/device-feedback
Cc: david@vielhuber.de
Betreff: Re: [device-feedback] Phonegap build (#1)

One thing... I had iPhone for two minutes a few days ago :-D, but I discover, there is not any acoustic touch feedback on buttons. But I thought iOS have acoustic touch feedback. How is it in real?

**Comment by VVelda** [comment]
Nor in the previous iOS versions, for example iOS 5?

Well, I created this plugin to create Phonegap apps with native Android apps
feedback. Users in many cases realize, that basic Phonegap app isn't the 
common Android app, but he don't know why.

But why to create version of plugin for iOS, if in iOS is no this kind of 
feedback?

Seriously, playing extra sound in iOS does not lead to native experience. 
This is why, I have not developed version for Windows Phone, because there 
isn't this feedback too.

I don't have known this is not present in iOS. Sorry.

---------- Původní zpráva ----------

Od: vielhuber notifications@github.com

Komu: VVelda/device-feedback device-feedback@noreply.github.com

Datum: 29. 10. 2014 21:34:44

Předmět: Re: [device-feedback] Phonegap build (#1)

"
Hello! 

They don’t have one in general, 

but we want through your awesome plugin one! 

Thanks in advance 

David 

---

e: david@vielhuber.demailto:david@vielhuber.de 

w: www.vielhuber.dehttp://www.vielhuber.de/ 

t: 089-21555122 

f: 089-21555122-9 

l: e=email, w=web, t=telefon, f=fax, l=legende 

---

Von: Jan Velecký [mailto:notifications@github.com] 

Gesendet: Mittwoch, 29. Oktober 2014 21:26 

An: VVelda/device-feedback 

Cc: david@vielhuber.de 

Betreff: Re: [device-feedback] Phonegap build (#1) 

One thing... I had iPhone for two minutes a few days ago :-D, but I 
discover, there is not any acoustic touch feedback on buttons. But I thought
iOS have acoustic touch feedback. How is it in real? 

— 

Reply to this email directly or view it on GitHub<https://github.com/VVelda/
device-feedback/issues/1#issuecomment-60998322>. 

—

Reply to this email directly or view it on GitHub
(https://github.com/VVelda/device-feedback/issues/1#issuecomment-60999800). 

"=

**Comment by vielhuber** [comment]
Hello Jan!

You are absolutely right with your argumentation.

Perhaps you can describe that also in the official github documentation.

Best greets
David

---

e: david@vielhuber.demailto:david@vielhuber.de
w: www.vielhuber.dehttp://www.vielhuber.de/
t: 089-21555122
f: 089-21555122-9

## l: e=email, w=web, t=telefon, f=fax, l=legende

Von: Jan Velecký [mailto:notifications@github.com]
Gesendet: Mittwoch, 29. Oktober 2014 21:59
An: VVelda/device-feedback
Cc: david@vielhuber.de
Betreff: Re: [device-feedback] Phonegap build (#1)

Nor in the previous iOS versions, for example iOS 5?

Well, I created this plugin to create Phonegap apps with native Android apps
feedback. Users in many cases realize, that basic Phonegap app isn't the
common Android app, but he don't know why.

But why to create version of plugin for iOS, if in iOS is no this kind of
feedback?

Seriously, playing extra sound in iOS does not lead to native experience.
This is why, I have not developed version for Windows Phone, because there
isn't this feedback too.

I don't have known this is not present in iOS. Sorry.

---------- Původní zpráva ----------

Od: vielhuber <notifications@github.com<mailto:notifications@github.com>>

Komu: VVelda/device-feedback <device-feedback@noreply.github.com<mailto:device-feedback@noreply.github.com>>

Datum: 29. 10. 2014 21:34:44

Předmět: Re: [device-feedback] Phonegap build (#1)

"
Hello!

They don’t have one in general,

but we want through your awesome plugin one!

Thanks in advance

David

---

e: david@vielhuber.demailto:david@vielhuber.de<mailto:david@vielhuber.de%3cmailto:david@vielhuber.de>

w: www.vielhuber.dehttp://www.vielhuber.de/<http://www.vielhuber.de%3chttp:/www.vielhuber.de/>

t: 089-21555122

f: 089-21555122-9

l: e=email, w=web, t=telefon, f=fax, l=legende

---

Von: Jan Velecký [mailto:notifications@github.com]

Gesendet: Mittwoch, 29. Oktober 2014 21:26

An: VVelda/device-feedback

Cc: david@vielhuber.demailto:david@vielhuber.de

Betreff: Re: [device-feedback] Phonegap build (#1)

One thing... I had iPhone for two minutes a few days ago :-D, but I
discover, there is not any acoustic touch feedback on buttons. But I thought
iOS have acoustic touch feedback. How is it in real?

—

Reply to this email directly or view it on GitHub<https://github.com/VVelda/
device-feedback/issues/1#issuecomment-60998322<https://github.com/VVelda/%0bdevice-feedback/issues/1#issuecomment-60998322>>.

—

Reply to this email directly or view it on GitHub
(https://github.com/VVelda/device-feedback/issues/1#issuecomment-60999800).

"=

**Comment by VVelda** [comment]
And that problem with plugin in Phonegap Build, it's look that it is now possible:
`<gap:plugin name="cz.velda.cordova.plugin.devicefeedback" source="plugins.cordova.io" />`
I discovered it here: http://docs.build.phonegap.com/en_US/configuring_plugins.md.html

So I'm closing this issue.

**Comment by VVelda** [comment]
License now should not be the problem too https://github.com/phonegap/build/issues/337
