### ISSUE TITLE
Use this as 3rd party plugin in Intel xdk

### ISSUE THREAD

**Issue by pratitisamriya** [VVelda/device-feedback#2]
Hi,

I need to use this as third party plugin while building android app with cordova from Intel xdk.
I added the plugin with the plugin add interface, and used the JS code to play sound as per your doc, but it didn't work.

I'm testing on Android 4.4.4 device.

**Comment by VVelda** [comment]
Hello.
What is Cordova version you use? And did you try demo project in your enviroment?

**Comment by pratitisamriya** [comment]
Hello,

I'm using Cordova 3.5.1.
Yes I did try demo project, that also didn't work.

**Comment by VVelda** [comment]
Sorry for delayed response (much study, work & ill). Could you test it in standard Cordova CLI project, if it works for you?

I don't have any experience with Intel XDK yet, so this will be useful information for me about this issue.
