### ISSUE TITLE
build failed with android cordova 4.0.0

### ISSUE THREAD

**Issue by puntsok** [VVelda/device-feedback#5]
I am having trouble compiling with the latest version of cordova android:

``` shell
Installed platforms: android 4.0.0
```

Most likely the problem is how the `CordovaWebView` no longer extends its parent in the same way as it did before.  Several other plugins are also dealing with the same issue (e.g. com.telerik.plugins.nativepagetransitions, de.appplant.cordova.plugin.local-notification). Here is the error section of output log upon `cordova build android`: 

``` shell
:compileArmv7DebugJava
/Users/cewalker/Sites/hello/platforms/android/src/cz/Velda/cordova/plugin/devicefeedback/DeviceFeedback.java:33: error: cannot find symbol
        webView.setSoundEffectsEnabled(false);
               ^
  symbol:   method setSoundEffectsEnabled(boolean)
  location: variable webView of type CordovaWebView
/Users/cewalker/Sites/hello/platforms/android/src/cz/Velda/cordova/plugin/devicefeedback/DeviceFeedback.java:56: error: cannot find symbol
            webView.performHapticFeedback(args.getInt(VIBRATE_TYPE_INDEX));
                   ^
  symbol:   method performHapticFeedback(int)
  location: variable webView of type CordovaWebView
2 errors
:compileArmv7DebugJava FAILED
```

Wish I could contribute a fix, but I'm not familiar enough with the android platform.  Is there a quick fix for this?

Cheers!

**Comment by VVelda** [comment]
Hello,
thanks for report, and sorry for delayed response, I'm doing exams at university these days...
Check this file, I edited it according to changes in the other plugins. I'm going to do it properly till end of month. This is only quick fix I haven't tested.

![devicefeedback](https://cloud.githubusercontent.com/assets/3459338/7594939/39e52872-f8e4-11e4-85e1-0ca188cacff7.png)
Download that file (PNG image) and name it DeviceFeedback.java and replace with that earlier file. I hope it will works for you.

**Comment by mtsgrd** [comment]
You can solve this by using e.g. `webView.getView().performHapticFeedback()`.

**Comment by mtsgrd** [comment]
https://github.com/VVelda/device-feedback/pull/6

**Comment by VVelda** [comment]
@mtsgrd: That would break backward compability – it was a little harder than your pull request and solution isn't pretty, but that is Java limitations... :-) 

I have uploaded it into master branch. I have tested it on duo cordova-cli/cordova-android 3.5.0/3.5.0 and 5.0.0/4.0.0, so now it should work on both older cordova-android and newer cordova-android.

Can someone confirm it, so I'll be able to upload it to Cordova Plugin Repository?

**Comment by mtsgrd** [comment]
@VVelda :+1:

**Comment by hervehobbes** [comment]
Hello, 

Same error for me with Cordova 5.1.1 (platform Android)

**Comment by VVelda** [comment]
Hi @hervethouzard,
could you said exact version fo cordova-cli (cordova -v) and cordova-android (cordova platform) and also exact version of this plugin (cordova plugin) – you should see here 0.0.2-test.

@puntsok could you please test it now too?

Thanks

**Comment by puntsok** [comment]
Appears to be working for me! I tested the `acoustic` method in the context of an app running on cordova version 5.1.1 with android platform 4.0.0. Thanks!

**Comment by VVelda** [comment]
Fix is proven.
