### ISSUE TITLE
Android 5 Haptic Feedback - Not Working

### ISSUE THREAD

**Issue by kaansoral** [VVelda/device-feedback#8]
On my Galaxy S4, after upgrading to Android 5.0.1, haptic feedback is not working, although it's enabled from settings

Before Android 5, there was no issues

Anyone in a similar situation?

**Comment by VVelda** [comment]
I cannot test on Android 5 device, but are you sure it is enabled? Please, check result of "Is feedback enabled" button in demo app.

**Comment by kaansoral** [comment]
Yes it is enabled, I just checked things further

It seems the power saving mode of the device was tampering with my experiments

So, somehow the power saving mode was on, and when power saving mode is on, it seems the haptic feedback doesn't play even though it's enabled

**Comment by VVelda** [comment]
So it is not issue at all. We can close this issue then, can't we?

**Comment by kaansoral** [comment]
Yes :)

On a separate note though, a function like is_haptic_feedback_available would be awesome, it's almost always enabled but almost never available (considering many devices aren't even capable of delivering one)
