### ISSUE TITLE
devicefeedback in <iframe or <embed tag?

### ISSUE THREAD

**Issue by maxlinux2000** [VVelda/device-feedback#9]
HI
I have an app in cordova that have part of them in an external server, and the users can interact with an iframe (or embed if necessary).

With the local files the devicefeedback works perfectly, but not in the iframe or in the embed tag...

Do you know if is possible to activate the devicefeedback in the remote files too?

regards
MaX

**Comment by kaansoral** [comment]
Your question is more along these lines: http://stackoverflow.com/questions/5477324/iframe-calling-parent-javascript

So it's not related to this plugin, it might be impossible too, you have to try and see in your scenario
